### PR TITLE
1.19.2 + Fix settings.gradle.kts versioning

### PR DESCRIPTION
**Pull request by GeeLeonidas**

### CODE REVIEW

**Comment by GeeLeonidas** [comment]
Hello there 👋
This PR should've been smaller, but I noticed that _settings.gradle.kts_ wasn't grabbing versions from _gradle.properties_ properly. I fixed it and made Kotlin versioning automatic, basing it on the version Fabric Language Kotlin is using. If you need something done in this PR before merging, you may ask me :)

**Comment by myoun** [comment]
Thank you for your contribution to this project.

**Review by myoun — APPROVED** [review]
The updated version seems to work well.

**Comment by GeeLeonidas** [comment]
Just a side note:
I'm noticing that I forgot to update "fabricloader" to ">=0.14.9" (see [fabric.mod.json from fabric-example-mod](https://github.com/FabricMC/fabric-example-mod/blob/242f56a70245d99e7463d3f76f4af8038398bd5a/src/main/resources/fabric.mod.json#L30)). It shouldn't raise any errors on its own, as it's just metadata to tell the user which version of Fabric they should use. If you want to, I can send a PR that fixes it.

**Pull request merged**
